source: ./docs
destination: ./docs/_site
theme: jekyll-theme-slate
title: WebThings Documentation
description: A guide to using and developing for the WebThings IoT Platform
baseurl: /docs
show_downloads: false
encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge
future: true
jailed: false
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
